### ISSUE TITLE
Re-encoding images problems on COMI

### ISSUE THREAD

**Issue by Anthiflo** [BLooperZ/nutcracker#12]
Hello, I have a problem with COMI while re-encoding graphics. There is 2 problems I found:

1. On the CMI (The Monkeys are listening...) screen, the white parts are visible on frame 1 while the rest of the picture is still not visible
2. Some object images have green (supposed to be transparent) around them. I didn't edit this images, and don't need to
3. Some object images seems to miss some colors

![Screenshots_1_COMI](https://user-images.githubusercontent.com/78505354/188951156-9986bbd7-f044-4c76-b06e-5d71469ba807.png)
![Screenshots_2_COMI](https://user-images.githubusercontent.com/78505354/188951161-eca335cc-e44a-43d7-ad45-e5fde8145f51.png)
![Screenshots_3_COMI](https://user-images.githubusercontent.com/78505354/188951163-427d29a1-99b5-46a5-9a12-8a258a9c8c2f.png)

I did the following commands:
nutcracker.exe sptum room decode --ref myfile\COMI.LA0
nutcracker.exe sptum room encode --ref myfile\COMI.LA0 COMI
nutcracker.exe sptum room build myfile\COMI.LA0 COMI

Did I do something wrong?

**Comment by BLooperZ** [comment]
Hi, thanks for reporting.
usually this problem is related to palette optimization most graphic editors do automatically. (I recommend using GraphicsGale as it does not do this)
were the images opened and saved using some editor (even if no changes were made)?
is this problem happens when just decoding and re-encoding the images as-is?

**Comment by Anthiflo** [comment]
For the first one (the CMI logo) I edited it with photoshop (the image was already in limited palette, I didn't change that). I edited an other image (Part 1 screen) and did not encounter any problem in-game.
For the other images (screenshots 2 et 3), I didn't edit this files nor opened them in an editor since I don't need to do anything to them.
I'll try to do a decoding/re-encoding without touching anything.

**Comment by Anthiflo** [comment]
OK so I did a decoding/re-encoding without touching any file and : 
- The CMI logo problem doesn't occur anymore, so it might be a problem with my edited file
- Transparency (green around items) and color problems (on the inventory) still occur though

Note : After opening the CMI logo in GraphicsGale, I see where are the problems, the palette actually have multiple times the same colors to make elements appear at different times. It's a pain to edit but now it works great :)

**Comment by BLooperZ** [comment]
Thank you, fixed.
could you please try again with latest update?

**Comment by Anthiflo** [comment]
I tried with the latest version :
The color problem (on the inventory) seems to be fixed, however the green around items is still there.

**Comment by BLooperZ** [comment]
The green around items is fixed now as well, thank you.

**Comment by Anthiflo** [comment]
Seems good now, thanks!
