### ISSUE TITLE
Nutcracker exe closes instantly

### ISSUE THREAD

**Issue by Drachenbauer** [BLooperZ/nutcracker#17]
Hello i have got an acer nitro 5 with windows 11 and i cannot run nutcracker.exe, it just opens a black window, that instantly closes after 1 sec.
How can i get it to work here?
Or is opening the exe not the right way and i have to use the commands from the readme somewhere else?
But the readme does not say, where to use the commands

**Comment by BLooperZ** [comment]
Hi, Nutcracker is a CLI (command line interface) application
As such, it should be opened via a terminal application, such as Windows Command Line (cmd) or Powershell
If you hold Shift while right clicking in windows directory, there will be an option to open that directory with Powershell.
than you can write the commands as instructed in readme (if nutcracker.exe is in another directory, you should prefix it with the appropriate path to it)

**Comment by Drachenbauer** [comment]
I finally extracted a spyfox file to get the graphics.
But not all graphics appear in the directory it created:
-8ll importand animal characters (Spyfox himself and all those, he can interact with)
-the little objects out of the jar, as prize for the foursome card game of the fat pig
-the playing cards of the fat pig
-all these random fun animations, that occur on the extra click points, that are not necessary for proceeding the story of the game

How can i get theese missing graphics?

**Comment by BLooperZ** [comment]
I believe the missing graphics are AKOS (animated costumes), which are still WIP and not exposed in the CLI yet.
It can be used with the source code downloaded from here but requires python, more information here: https://github.com/BLooperZ/nutcracker/issues/13
(please also note there are some issues with colors)

**Comment by Drachenbauer** [comment]
How do i use this source code with python, that the command in the linked page works?
I have got python 3.11.0 and the pycharm python ide

The command points to a LA0 file of the game date, but i don´t see such at the spyfox files.

**Comment by BLooperZ** [comment]
you can install the latest version as a python library using ```pip install -U git+git://github.com/blooperz/nutcracker.git@develop```

The command should point to the index file, which is numbered 0, it can appear as .000, .LA0 or .HE0 depending on the game (Spy Fox should have HE0)
