### ISSUE TITLE
COMI: font encoding issue?

### ISSUE THREAD

**Issue by iokaravas** [BLooperZ/nutcracker#26]
I want to start by saying thank you very much for the time you've spent working on this @BLooperZ and contributors alike!

I'm trying to make a fan translation of Curse of Monkey Island in Greek and I've stumbled upon an issue.
I successfully extracted the strings and font `FONT1.NUT` and figured I could replace some unicode characters that are not really used in the game with Greek letters to use for my translation.

I did a small test changing the `ÀÁÂÃ` to `ΑΒΓΔ` for the first spoken line of Guybrush:

`/CNGT001/ÀÁÂÃ ÀÁÂÃ ÀÁÂÃ ÀÁÂÃ ÀÁÂÃ`

I substituted the characters as shown here:
![image](https://github.com/user-attachments/assets/0a72c6b3-8c47-4e6f-8d9f-5e17aecbf8d2)

Then injected the text, encoded the font and replaced the original files with the modded ones and got this:
![CNGT001_GREEK](https://github.com/user-attachments/assets/a7ef00f2-03d3-4de7-8397-29aa38267994)

I was expecting to get `ΑΒΓΔ ΑΒΓΔ ΑΒΓΔ ΑΒΓΔ ΑΒΓΔ` .

I only replaced `FONT1.NUT` because this seems to be the font used at least at the beginning of the game.
Also note I'm using the GOG version of the game (not sure if there are multiple versions out there)

Am I doing something wrong?

Thanks again for your time :)

**Comment by BLooperZ** [comment]
Glad to hear you find the tool useful🙂

I think the issue is caused by using wrong encoding in the test text, (according to the screenshot, I suspect the text is saved as UTF-8)

For this test you can saving as windows-1252 or latin-1.
but I recommend you try writing in greek and save as windows-1253
and, in the font, put the characters at the same places as shown in the table here https://en.m.wikipedia.org/wiki/Windows-1253

Please let me know if it works for you and feel free to contact me for further issues

**Comment by iokaravas** [comment]
Oh nice! I didn't thought of this :P
Thanks! Will be commenting back with the results.

**Comment by iokaravas** [comment]
This seems to be working!

One more thing, I know this is probably not the place to ask but where can I find more information about the png file that's exported and how to edit it properly? I just created black boxes of the same size (20x30) to place the letters on- from my understanding the height needs to always be 30? The width can vary?

Here's my capitals-only test. Thank you in advance!

![image](https://github.com/user-attachments/assets/9c93f338-84c2-4286-a93a-dab15dbe470e)
![image](https://github.com/user-attachments/assets/cdd7a2d0-1bd0-488b-bec3-bd1337e822af)

**Comment by BLooperZ** [comment]
The width of the character bounding box can and should vary as it controls the width of the character on display (how much spacing the character will have from the character to the left and to the right)... the height can also vary, but it will be easier to keep it constant... the bounding box starts in each cell at offset of 8 pixels from left and from top, IIRC it could also move, but again, easier to keep it in place.
The outer 16x16 checkers grid should remain as is.

I recommend editing the image with GraphicsGale as it does not do color palette optimization... IIRC, it is specifically important in this case, as there are actually several palette entry that are mapped to black.
To make it easier, you can replace the color of the first index to something more visible, and restore it after you are done editing.

**Comment by iokaravas** [comment]
I'm using Photoshop but I tried GraphicsGale and I do not see anything special other than the indexed palette being used. Am I missing something? The area around the letters is just #000 and I don't see any other colors used around them, asking because It seems strange the original fonts are shadowed nicely while new characters are completely blocked out with black color.

![image](https://github.com/user-attachments/assets/4db72bc7-5baa-4a5b-822e-4a308592d889)
![image](https://github.com/user-attachments/assets/411e70cc-1783-41be-822d-3935adaaf8d7)

Sorry it feels like I'm hijacking the issue a little bit- I hope you don't mind.
Thanks in advance!

**Comment by BLooperZ** [comment]
Have you opened a fresh image created by this tool or after it was opened/saved using Photoshop?
If it was saved using Photoshop then the palette was optimized and all black pixels have the same value
Opening a fresh image in GraphicsGale shows the pixels close to the letters have index 0, and the bounding rectangle have index 39
![image](https://github.com/user-attachments/assets/4eaa50f0-34ab-4a7b-a8de-39d13ffad7c4)
(In this image I have opened with GraphicsGale and changed index 39 to another color)

**Comment by iokaravas** [comment]
@BLooperZ Thanks again! I think I understand now.
