### ISSUE TITLE
COMI: Missing text when extracting strings

### ISSUE THREAD

**Issue by iokaravas** [BLooperZ/nutcracker#27]
I've extracted the Curse Of Monkey Island script text using:

`nutcracker sputm strings_extract --textfile strings.txt COMI.LA0`

But playing the game I see there's dialogue text and spoken text that is not in the `strings.txt` file.

![image](https://github.com/user-attachments/assets/51fe7ce4-d50e-41ad-92d6-325407a5e845)

This line for example- or many parts of the dialogue you have with Wally.

Confirmed my suspicions through the LANGUAGE.TAB file (GOG version) containing a lot more lines and potentially all text. But that file does not support a non-Unicode character set and Unicode doesn't map properly to the font sprites.

**Comment by BLooperZ** [comment]
Actually, saving LANGUAGE.TAB in windows-1253 (greek) encoding should work as expected

(there is no need to use strings_extract/inject for this game as LANGUAGE.TAB have everything)

**Comment by iokaravas** [comment]
> Actually, saving LANGUAGE.TAB in windows-1253 (greek) encoding should work as expected
> 
> (there is no need to use strings_extract/inject for this game as LANGUAGE.TAB have everything)

Well I'm a victim of "bad" software once more. Notepad++ did the job. Sublime Text screwed up the file.

I do not know if I should be closing this , I guess it doesn't matter if nutcracker doesn't export everything as the .TAB file works fine... I'll leave it up to you!

Thanks again! Now to translate ~10.000 lines 🥇

**Comment by BLooperZ** [comment]
Good luck 😁🙏
If you'd like, there are also bit more than 30 backgrounds with texts
and the title in the opening video 🙃
