### ISSUE TITLE
Error while unpacking images from COMI.LA0

### ISSUE THREAD

**Issue by AtsushiShiga** [BLooperZ/nutcracker#3]
Having issues while trying to decode room/object images from "The Curse of the Monkey Island" (SCUMM v8) (tried both CD and GOG versions)
Launching nutcracker through git.bash (the latest ver. of python is used), but as decoding process begins, it abruptly terminates with an error.
ValueError: bytes must be in range(0, 256), to be clear.
But this tool manages to unpack first two rooms from the first data file. As far as I'm concerned, the next ones are title cards (according to SCUMM revisited), so they cause decoding process to stop. Hope this will be solved, as it is vital for proper translation of the game.

**Comment by BLooperZ** [comment]
Thank you, fixed
